#!/bin/sh
# Copyright (C) 2006 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

# commands for emitting messages to network in failsafe mode

indicate_failsafe() {
	[ "$pi_preinit_no_failsafe" = "y" ] && return
	echo "- failsafe -"
}

boot_hook_add failsafe indicate_failsafe
