#!/bin/sh
# Copyright (C) 2006 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

preinit_net_echo() {
	true
}

preinit_echo() {
	preinit_net_echo $1
	echo $1
}

pi_indicate_preinit() {
	preinit_net_echo "Doing OpenWrt Preinit\n"
	set_state preinit
}

boot_hook_add preinit_main pi_indicate_preinit
