#!/bin/sh
# Copyright (C) 2006 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

do_restore_config() {
	# If WPS button is not pressed (logic inversion with that tool...) restore config.
	if evstate /dev/event0 key 529; then
		restore-config
	fi
}

boot_hook_add preinit_main do_restore_config
